--- Test authorization methods of our API ---

--- Use login resource to retrieve a bearer token, check that calls require
authorization first, then supply token and check we can access resources now.
Create API key and secret and check authorization works with those too

[FIXME] Can't create a basic auth token from that pair from within blueprint at this
point.
---

POST /login
> Content-type: application/json
{
  "username": "{{<username}}",
  "password": "{{<password}}"
}
< 200
< Content-type: application/json
{
  "token": "{{>token}}"
}

GET /metrics
< 401
< Content-type: application/json
{
  "code": "AUTHORIZATION_HEADER_ERROR"
}

GET /metrics
> Authorization: Bearer {{<token}}
< 200
< Content-type: application/json
[{
  "node": "{{_}}"
}]

POST /api_key
> Authorization: Bearer {{<token}}
> Content-type: application/json
{
  "name": "my_api_key",
  "desc": "fix me, this is a bug in the schema or code since it's optional in schema but required by code",
  "enable": true
}
< 200
< Content-type: application/json
{
  "name": "my_api_key",
  "api_key": "{{>api_key}}",
  "api_secret": "{{>api_secret}}"
}

# GET /api_key
# > Authorization: Basic { "{{type}}": "runtime_value", "erlang": "base64(lists:flatten([{{>api_key}}, \":\", {{>api_secret}}]))" }
# < 200

DELETE /api_key/my_api_key
> Authorization: Bearer {{<token}}
< 204